variables:
  S3_BUCKET_PRODUCTION: "BookingApp"
  S3_KEY_PRODUCTION: "frontend"

deploy production:
  stage: build
  image: nikolaik/python-nodejs:latest
  script:
  - yarn
  - yarn test
  - yarn build
  - pip install awscli
  - aws s3 cp ./build/ s3://$S3_BUCKET_PRODUCTION/$S3_KEY_PRODUCTION --recursive --include "*"
  - echo "Deploying"
  artifacts:
      paths:
      - build
  environment:
      name: production
      url: http://giwoolee.s3-website.us-east-2.amazonaws.com
  only:
  - master
